# Stable kernel-development reference.
TARGET_ARCH=arm32
TARGET_PLATFORM=qemu-virt
SMP_CPUS=4
ENABLE_NET=no
ENABLE_GPU=yes
BUILD_NEWLIB=yes
BUILD_TCC=yes
BUILD_BSD=yes
BUILD_NCURSES=yes
BUILD_NANO=yes
