# AArch64 kernel-feature reference.
TARGET_ARCH=arm64
TARGET_PLATFORM=qemu-virt
SMP_CPUS=4
KEYBOARD_LAYOUT=fr-mac
ENABLE_NET=yes
ENABLE_GPU=yes
QEMU_GPU_ACCEL=virgl
QEMU_GPU_HOSTMEM=512M
BUILD_NEWLIB=yes
BUILD_TCC=yes
BUILD_BSD=yes
BUILD_NCURSES=yes
BUILD_NANO=yes
BUILD_EPOLL_SHIM=yes
BUILD_PIXMAN=yes
BUILD_TLLIST=yes
BUILD_UTF8PROC=yes
BUILD_FREETYPE=yes
BUILD_EXPAT=yes
BUILD_FONTCONFIG=yes
BUILD_HARFBUZZ=yes
BUILD_FCFT=yes
BUILD_FOOT=yes
BUILD_NUKLEAR=yes
BUILD_MESA=yes
