# Raspberry Pi 3 B+ hardware reference.
TARGET_ARCH=arm64
TARGET_PLATFORM=raspi3
SMP_CPUS=4
KEYBOARD_LAYOUT=fr-legacy
ENABLE_NET=yes
ENABLE_GPU=no
ENABLE_HDMI=yes
ENABLE_WIFI=yes
HDMI_WIDTH=1280
HDMI_HEIGHT=720
ENABLE_ILI9341=yes
ENABLE_USB=yes
BUILD_NEWLIB=yes
BUILD_TCC=yes
BUILD_BSD=yes
BUILD_NCURSES=yes
BUILD_NANO=yes
BUILD_EPOLL_SHIM=yes
BUILD_PIXMAN=yes
BUILD_TLLIST=yes
BUILD_UTF8PROC=yes
BUILD_FREETYPE=yes
BUILD_EXPAT=yes
BUILD_FONTCONFIG=yes
BUILD_HARFBUZZ=yes
BUILD_FCFT=yes
BUILD_FOOT=yes
BUILD_ZLIB=yes
BUILD_LIBJPEG=yes
BUILD_LIBPNG=yes
BUILD_LIBTIFF=yes
BUILD_FBVIEW=yes
BUILD_XV_DEPS=yes
DEVICE_TREE=bcm2710-rpi-3-b-plus.dtb
DTOVERLAY=disable-bt
