# Raspberry Pi 2 Model B v1.1 / QEMU raspi2 target.
TARGET_ARCH=arm32
TARGET_PLATFORM=raspi2
SMP_CPUS=4
KEYBOARD_LAYOUT=fr-legacy
ENABLE_NET=no
ENABLE_GPU=no
ENABLE_HDMI=yes
HDMI_WIDTH=1280
HDMI_HEIGHT=720
ENABLE_ILI9341=no
ENABLE_USB=yes
BUILD_NEWLIB=yes
BUILD_TCC=yes
BUILD_BSD=yes
BUILD_NCURSES=yes
BUILD_LIBEDIT=yes
BUILD_FREEBSD_SH=yes
BUILD_FREEBSD_TOP=yes
BUILD_NANO=yes
BUILD_EPOLL_SHIM=yes
BUILD_PIXMAN=yes
BUILD_TLLIST=yes
BUILD_UTF8PROC=yes
BUILD_FREETYPE=yes
BUILD_EXPAT=yes
BUILD_FONTCONFIG=yes
BUILD_HARFBUZZ=yes
BUILD_FCFT=yes
BUILD_FOOT=yes
BUILD_NUKLEAR=yes
DEVICE_TREE=bcm2709-rpi-2-b.dtb
